spring:
  application:
    name: time-client  # 应用名

server:
  port: 9090 # 端口

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    register-with-eureka: false # 纯粹的消费端，就不注册了