spring:
  application:
    name: feign-client-02  # 应用名

server:
  port: 9090 # 端口

feign:
  httpclient:
    enabled: true # 使用 apache httpclient

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    # 6. 从 注册中心拉取服务列表的时间间隔 -- 从 30s 改为 3s
    registry-fetch-interval-seconds: 3

  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    # 5. 发送心跳时间间隔 -- 从 30s 改为 3s
    lease-renewal-interval-in-seconds: 3
    # 4. 实例过期时间间隔 从 90s 改为 9s 或者 6s
    leaseExpirationDurationInSeconds: 6

feign-service-02:
  ribbon:
    ServerListRefreshInterval: 3000